### ISSUE TITLE
Topic Model update!

### ISSUE THREAD

**Issue by komanderb** [komanderb/Dipromats24#1]
For the topic model, can you check the differences in topics from countries and make a nice plot?

**Comment by AntoniValls** [comment]
I update the TopicModel.py file.

A screenshot of the plot with the top10 topics selected is here. 
![imagen](https://github.com/komanderb/Dipromats24/assets/101109878/69f8b2a8-9304-4ec3-8cbd-b165fb1d5cf6)

I also send you the .html file via whatsapp in case you want to interact with it.

-----
**Update about other stuff:**
ACLED: I have been checking different combinations of the dataset and I have obtained about 0.35 of correlation between the events and the use of propaganda (which I think is pretty good).

From the topic analysis it seems clear that we should also incorporate some covid data and some sanctions data. About covid data, most of the tweets about it talk about the covid situation in their regions so having some kind of Covid evolution restricted to this 4 zones may be enough. About sanctions, I have already contact with https://www.globalsanctionsdatabase.com/ whose dataset seems that can be useful.

 So maybe, in the end we will have a ACLED + COVID + SANCTIONS dataset that will cover most of the geopolitical context. If you think about other stuff that we may take into account, tell me.

**Comment by komanderb** [comment]
amazing!
